### ISSUE TITLE
Output is unstable

### ISSUE THREAD

**Issue by gabriel** [keybase/node-avdl2json#4]
I've seen it output:

```
{
  "protocol": "block",
  "types": [ ... ],
  "namespace": "keybase.1"
}
```

And in a slightly different order:

```
{
  "namespace": "keybase.1",
  "protocol": "block",
  "types": [ ... ]
}
```

The map entries should be consistently ordered in some way?

**Comment by maxtaco** [comment]
this just changed between v1.2 and v1.3

**Comment by maxtaco** [comment]
(otherwise it's stable!)
